server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/librarymanagement
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8

